/* $Id$ */

/* ********* Automatically Generated.  Do not edit! ******** */
/* *********         Created with html2c            ******** */

fprintf(fp,"%%!PS-Adobe-3.0\n");
fprintf(fp,"%%%%Creator: WaveCalc\n");
fprintf(fp,"%%%%BoundingBox: 0 0 %g %g\n",rint(72*paperwidth),rint(72*paperheight));
fprintf(fp,"%%%%PageBoundingBox: 0 0 %g %g\n",rint(72*paperwidth),rint(72*paperheight));
fprintf(fp,"%%%%EndComments\n");
fprintf(fp,"%%%%BeginProlog\n");
fprintf(fp,"%%\n");
fprintf(fp,"%% Select the font\n");
fprintf(fp,"/currfont /Times-Roman findfont def\n");
fprintf(fp,"%% \n");
fprintf(fp,"%% Set font size\n");
fprintf(fp,"/fsize %g def\n",fontsize);
fprintf(fp,"currfont fsize scalefont setfont\n");
fprintf(fp,"\n");
fprintf(fp,"%%\n");
fprintf(fp,"%% Set line spacing\n");
fprintf(fp,"%%\n");
fprintf(fp,"/linespace 1.0 def\n");
fprintf(fp,"%%\n");
fprintf(fp,"%% inches to postscript unit conversion\n");
fprintf(fp,"/inch {72 mul} def\n");
fprintf(fp,"%%\n");
fprintf(fp,"\n");
fprintf(fp,"%%\n");
fprintf(fp,"/leftcol %g inch def\n",leftmargin);
fprintf(fp,"\n");
fprintf(fp,"%%\n");
fprintf(fp,"%% wrapper around eps files inclusion\n");
fprintf(fp,"%%\n");
fprintf(fp,"/BEGINEPSFILE {%%def\n");
fprintf(fp,"  /EPSFsave save def\n");
fprintf(fp,"  0 setgray 0 setlinecap 1 setlinewidth 0 setlinejoin \n");
fprintf(fp,"  10 setmiterlimit [] 0 setdash\n");
fprintf(fp,"  newpath\n");
fprintf(fp,"  /showpage {} def\n");
fprintf(fp,"} bind def\n");
fprintf(fp,"/ENDEPSFILE {%%def\n");
fprintf(fp,"  EPSFsave restore\n");
fprintf(fp,"} bind def\n");
fprintf(fp,"\n");
fprintf(fp,"%%\n");
fprintf(fp,"%% Various useful functions for printing\n");
fprintf(fp,"%% text\n");
fprintf(fp,"\n");
fprintf(fp,"/centercentershow {\n");
fprintf(fp,"dup\n");
fprintf(fp,"stringwidth\n");
fprintf(fp,"pop\n");
fprintf(fp,"2 div neg  fsize 2 div neg rmoveto\n");
fprintf(fp,"show\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"/rightcentershow {\n");
fprintf(fp,"dup\n");
fprintf(fp,"stringwidth\n");
fprintf(fp,"pop\n");
fprintf(fp,"neg  fsize 2 div neg rmoveto\n");
fprintf(fp,"show\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"%% puts the centertop of the text at the current point\n");
fprintf(fp,"/centertopshow {\n");
fprintf(fp,"dup\n");
fprintf(fp,"stringwidth\n");
fprintf(fp,"pop\n");
fprintf(fp,"2 div neg fsize  neg rmoveto\n");
fprintf(fp,"show\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"%% puts the centerbot of the text at the current point\n");
fprintf(fp,"/centerbotshow {\n");
fprintf(fp,"dup\n");
fprintf(fp,"stringwidth\n");
fprintf(fp,"pop\n");
fprintf(fp,"2 div neg fsize  rmoveto\n");
fprintf(fp,"show\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"%% draw an open box.stack: centerx,centery,width,height\n");
fprintf(fp,"%%/boxcenter {\n");
fprintf(fp,"%%  newpath moveto\n");
fprintf(fp,"%%  $printwidth  inch  0 inch rlineto\n");
fprintf(fp,"%%  0 inch -$labelheight inch rlineto\n");
fprintf(fp,"%%  -$printwidth  inch  0 inch rlineto\n");
fprintf(fp,"%%  0 inch  $labelheight inch rlineto\n");
fprintf(fp,"%%  closepath\n");
fprintf(fp,"%%  1 setlinewidth\n");
fprintf(fp,"%%  stroke\n");
fprintf(fp,"%%} def\n");
fprintf(fp,"\n");
fprintf(fp,"%% newline command\n");
fprintf(fp,"/newline {\n");
fprintf(fp,"  currentpoint\n");
fprintf(fp,"  fsize linespace mul sub \n");
fprintf(fp,"  exch pop leftcol exch\n");
fprintf(fp,"  moveto\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"%% newlinecenter command\n");
fprintf(fp,"/newlinecenter {\n");
fprintf(fp,"  currentpoint\n");
fprintf(fp,"  fsize linespace mul sub \n");
fprintf(fp,"  exch pop %g 2 div inch exch\n",paperwidth);
fprintf(fp,"  moveto\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"\n");
fprintf(fp,"/tab1{\n");
fprintf(fp,"    currentpoint exch pop \n");
fprintf(fp,"    %g inch leftcol add exch \n",tab1);
fprintf(fp,"    moveto\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"/tab2{\n");
fprintf(fp,"    currentpoint exch pop \n");
fprintf(fp,"    %g inch leftcol add exch \n",tab2);
fprintf(fp,"    moveto\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"/tab3{\n");
fprintf(fp,"    currentpoint exch pop \n");
fprintf(fp,"    %g inch leftcol add exch \n",tab3);
fprintf(fp,"    moveto\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"/tab4{\n");
fprintf(fp,"    currentpoint exch pop \n");
fprintf(fp,"    %g inch leftcol add exch \n",tab4);
fprintf(fp,"    moveto\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"\n");
fprintf(fp,"/symbolshow {\n");
fprintf(fp,"  /Symbol findfont fsize scalefont setfont\n");
fprintf(fp,"  show\n");
fprintf(fp,"  currfont fsize scalefont setfont\n");
fprintf(fp,"} def\n");
fprintf(fp,"\n");
fprintf(fp,"%%%%EndProlog\n");
fprintf(fp,"%%%%BeginSetup\n");
fprintf(fp,"%%%%EndSetup\n");
fprintf(fp,"%%%%Page: 1 1\n");
fprintf(fp,"\n");
fprintf(fp,"%%\n");
fprintf(fp,"%% The header on the page\n");
fprintf(fp,"%%\n");
fprintf(fp,"%g 2 div inch %g %g sub inch moveto\n",paperwidth,paperheight,topmargin);
fprintf(fp,"%%\n");
fprintf(fp,"%% larger font\n");
fprintf(fp,"currfont fsize 2.0 mul scalefont setfont\n");
fprintf(fp,"(WaveCalc:  Version-0.1) centertopshow newlinecenter\n");
fprintf(fp,"(Microstrip Analysis/Synthesis) centertopshow newlinecenter\n");
fprintf(fp,"newlinecenter\n");
fprintf(fp,"currfont fsize scalefont setfont\n");
fprintf(fp,"\n");
fprintf(fp,"%%  \n");
fprintf(fp,"%% The figure of the structure being analyzed\n");
fprintf(fp,"%%\n");
fprintf(fp,"\n");
fprintf(fp,"%%\n");
fprintf(fp,"%% We are currently where the top center of the figure should be.\n");
fprintf(fp,"%% First figure out where the text will be when we continue\n");
fprintf(fp,"%% after the figure\n");
fprintf(fp,"%%\n");
fprintf(fp,"currentpoint %d %d sub sub\n",bbox_ury,bbox_lly);
fprintf(fp,"gsave\n");
fprintf(fp,"currentpoint pop %d %d add 2 div sub\n",bbox_llx, bbox_urx);
fprintf(fp,"currentpoint exch pop %d sub \n",bbox_ury);
fprintf(fp,"translate\n");
fprintf(fp,"%%\n");
fprintf(fp,"%%include the EPS file\n");
fprintf(fp,"%%\n");
fprintf(fp,"BEGINEPSFILE\n");
fprintf(fp,"\n");


#include "ps_microstrip.c"


fprintf(fp,"\n");
fprintf(fp,"ENDEPSFILE\n");
fprintf(fp,"grestore\n");
fprintf(fp,"moveto\n");
fprintf(fp,"%% spit out the numbers\n");
fprintf(fp,"newline\n");
fprintf(fp,"newline\n");
fprintf(fp,"newline\n");
fprintf(fp,"/col1x currentpoint pop def\n");
fprintf(fp,"/col2x currentpoint pop %g inch 2 div add def\n",paperwidth);
fprintf(fp,"/coly currentpoint exch pop def\n");
fprintf(fp,"/linespace 1.5 def\n");
fprintf(fp,"\n");
fprintf(fp,"col1x coly moveto\n");
fprintf(fp,"/leftcol col1x  def\n");
fprintf(fp,"(W) show tab1 (=) show tab2 (50 mils) show newline\n");
fprintf(fp,"(H) show tab1 (=) show tab2 (62 mils) show newline\n");
fprintf(fp,"(L) show tab1 (=) show tab2 (1000 mils ) show newline\n");
fprintf(fp,"newline\n");
fprintf(fp,"(Tmet) show tab1 (=) show tab2 (1.4 mils) show newline\n");
fprintf(fp,"(Rho) show tab1 (=) show tab2 (1) show newline\n");
fprintf(fp,"(Rough) show tab1 (=) show tab2 (0.05 mils-rms) show newline\n");
fprintf(fp,"(e) symbolshow (r) show tab1 (=) show tab2 (4.8) show newline\n");
fprintf(fp,"(tan) show (d) symbolshow tab1 (=) show tab2 (0.01) show newline\n");
fprintf(fp,"\n");
fprintf(fp,"col2x coly moveto \n");
fprintf(fp,"/leftcol col2x def\n");
fprintf(fp,"(Z0) show tab1 (=) show tab2 (50 ) show (W) symbolshow newline\n");
fprintf(fp,"(keff) show tab1 (=) show tab2 (3.38 ) show newline\n");
fprintf(fp,"(elen) show tab1 (=) show tab2 ( deg) show newline\n");
fprintf(fp,"(Loss) show tab1 (=) show tab2 ( dB) show newline\n");
fprintf(fp,"(Loss/Len) show tab1 (=) show tab2 ( dB/mil) show newline\n");
fprintf(fp,"(skin depth) show tab1 (=) show tab2 (mil) show newline\n");
fprintf(fp,"newline\n");
fprintf(fp,"(Ls) show tab1 (=) show tab2 (nH/mil) show newline\n");
fprintf(fp,"(Rs) show tab1 (=) show tab2 (W) symbolshow (/mil) show newline\n");
fprintf(fp,"(Cs) show tab1 (=) show tab2 (pF/mil) show newline\n");
fprintf(fp,"(Gs) show tab1 (=) show tab2 (1/) show (W) symbolshow (-mil) show newline\n");
fprintf(fp,"\n");
fprintf(fp,"%%\n");
fprintf(fp,"%% All done with data output.\n");
fprintf(fp,"%%\n");
fprintf(fp,"\n");
fprintf(fp,"%%\n");
fprintf(fp,"%% add the time stamp\n");
fprintf(fp,"%%\n");
fprintf(fp,"\n");
fprintf(fp,"%g inch 2 div\n",paperwidth);
fprintf(fp,"%g inch \n",bottommargin);
fprintf(fp,"moveto\n");
fprintf(fp,"(%s) centerbotshow\n",ctime(&now));
fprintf(fp,"\n");
fprintf(fp,"showpage\n");
fprintf(fp,"\n");
fprintf(fp,"%%%%Trailer\n");
fprintf(fp,"%%MatchingCreationDate: \n");
fprintf(fp,"%%%%DocumentFonts: Symbol\n");
fprintf(fp,"%%%%+ Helvetica Times-Roman\n");
fprintf(fp,"%%%%EOF\n");

/* *********        End of Generated Code           ******** */

