/* $Id$ */

fprintf(fp,"%% We are currently where the top center of the figure should be.\n");
fprintf(fp,"%% First figure out where the text will be when we continue\n");
fprintf(fp,"%% after the figure\n");
fprintf(fp,"%%\n");
fprintf(fp,"currentpoint %d %d sub sub\n",bbox_ury,bbox_lly);
fprintf(fp,"gsave\n");
fprintf(fp,"currentpoint pop %d %d add 2 div sub\n",bbox_llx, bbox_urx);
fprintf(fp,"currentpoint exch pop %d sub \n",bbox_ury);
fprintf(fp,"translate\n");
fprintf(fp,"%%\n");
fprintf(fp,"%%include the EPS file\n");
fprintf(fp,"%%\n");
fprintf(fp,"BEGINEPSFILE\n");
fprintf(fp,"\n");

/* ********* Automatically Generated.  Do not edit! ******** */
/* *********         Created with html2c            ******** */

fprintf(fp,"%%!PS-Adobe-3.0 EPSF-3.0\n");
fprintf(fp,"%%%%BoundingBox: 101 664 309 775\n");
fprintf(fp,"%%%%Title: microstrip\n");
fprintf(fp,"%%%%CreationDate: Sat Sep 15 16:16:24 2001\n");
fprintf(fp,"%%%%Creator: Tgif-4.1.40 by William Chia-Wei Cheng (william@cs.UCLA.edu)\n");
fprintf(fp,"%%%%ProducedBy: (unknown)\n");
fprintf(fp,"%%%%Pages: 1\n");
fprintf(fp,"%%%%DocumentFonts: (atend)\n");
fprintf(fp,"%%%%EndComments\n");
fprintf(fp,"%%%%BeginProlog\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifdict 86 dict def\n");
fprintf(fp,"tgifdict begin\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifarrowtipdict 8 dict def\n");
fprintf(fp,"tgifarrowtipdict /mtrx matrix put\n");
fprintf(fp,"\n");
fprintf(fp,"/TGAT %% tgifarrowtip\n");
fprintf(fp," { tgifarrowtipdict begin\n");
fprintf(fp,"      /dy exch def\n");
fprintf(fp,"      /dx exch def\n");
fprintf(fp,"      /h exch def\n");
fprintf(fp,"      /w exch def\n");
fprintf(fp,"      /y exch def\n");
fprintf(fp,"      /x exch def\n");
fprintf(fp,"      /savematrix mtrx currentmatrix def\n");
fprintf(fp,"      x y translate\n");
fprintf(fp,"      dy dx atan rotate\n");
fprintf(fp,"      0 0 moveto\n");
fprintf(fp,"      w neg h lineto\n");
fprintf(fp,"      w neg h neg lineto\n");
fprintf(fp,"      savematrix setmatrix\n");
fprintf(fp,"   end\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifpatdict 10 dict def\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifpatbyte\n");
fprintf(fp," { currentdict /retstr get exch\n");
fprintf(fp,"   pat i cellsz mod get put\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/tgifpatproc\n");
fprintf(fp," { 0 1 widthlim {tgifpatbyte} for retstr\n");
fprintf(fp,"   /i i 1 add def\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/TGPF %% tgifpatfill\n");
fprintf(fp," { tgifpatdict begin\n");
fprintf(fp,"      /h exch def\n");
fprintf(fp,"      /w exch def\n");
fprintf(fp,"      /lty exch def\n");
fprintf(fp,"      /ltx exch def\n");
fprintf(fp,"      /cellsz exch def\n");
fprintf(fp,"      /pat exch def\n");
fprintf(fp,"\n");
fprintf(fp,"      /widthlim w cellsz div cvi 1 sub def\n");
fprintf(fp,"      /retstr widthlim 1 add string def\n");
fprintf(fp,"      /i 0 def\n");
fprintf(fp,"\n");
fprintf(fp,"      tgiforigctm setmatrix\n");
fprintf(fp,"      ltx lty translate\n");
fprintf(fp,"      w h true [1 0 0 1 0 0] {tgifpatproc} imagemask\n");
fprintf(fp,"      ltx neg lty neg translate\n");
fprintf(fp,"   end\n");
fprintf(fp," } def\n");
fprintf(fp,"\n");
fprintf(fp,"/pat3 <8000000008000000> def\n");
fprintf(fp,"/pat4 <8800000022000000> def\n");
fprintf(fp,"/pat5 <8800220088002200> def\n");
fprintf(fp,"/pat6 <8822882288228822> def\n");
fprintf(fp,"/pat7 <aa55aa55aa55aa55> def\n");
fprintf(fp,"/pat8 <77dd77dd77dd77dd> def\n");
fprintf(fp,"/pat9 <77ffddff77ffddff> def\n");
fprintf(fp,"/pat10 <77ffffff77ffffff> def\n");
fprintf(fp,"/pat11 <7fffffff7fffffff> def\n");
fprintf(fp,"/pat12 <8040200002040800> def\n");
fprintf(fp,"/pat13 <40a00000040a0000> def\n");
fprintf(fp,"/pat14 <ff888888ff888888> def\n");
fprintf(fp,"/pat15 <ff808080ff080808> def\n");
fprintf(fp,"/pat16 <f87422478f172271> def\n");
fprintf(fp,"/pat17 <038448300c020101> def\n");
fprintf(fp,"/pat18 <081c22c180010204> def\n");
fprintf(fp,"/pat19 <8080413e080814e3> def\n");
fprintf(fp,"/pat20 <8040201008040201> def\n");
fprintf(fp,"/pat21 <8844221188442211> def\n");
fprintf(fp,"/pat22 <77bbddee77bbddee> def\n");
fprintf(fp,"/pat23 <c1e070381c0e0783> def\n");
fprintf(fp,"/pat24 <7fbfdfeff7fbfdfe> def\n");
fprintf(fp,"/pat25 <3e1f8fc7e3f1f87c> def\n");
fprintf(fp,"/pat26 <0102040810204080> def\n");
fprintf(fp,"/pat27 <1122448811224488> def\n");
fprintf(fp,"/pat28 <eeddbb77eeddbb77> def\n");
fprintf(fp,"/pat29 <83070e1c3870e0c1> def\n");
fprintf(fp,"/pat30 <fefdfbf7efdfbf7f> def\n");
fprintf(fp,"/pat31 <7cf8f1e3c78f1f3e> def\n");
fprintf(fp,"\n");
fprintf(fp,"/TGMAX\n");
fprintf(fp," { exch dup 3 1 roll exch dup 3 1 roll gt { pop } { exch pop } ifelse\n");
fprintf(fp," } def\n");
fprintf(fp,"/TGMIN\n");
fprintf(fp," { exch dup 3 1 roll exch dup 3 1 roll lt { pop } { exch pop } ifelse\n");
fprintf(fp," } def\n");
fprintf(fp,"/TGSW { stringwidth pop } def\n");
fprintf(fp,"\n");
fprintf(fp,"/bd { bind def } bind def\n");
fprintf(fp,"\n");
fprintf(fp,"/GS { gsave } bd\n");
fprintf(fp,"/GR { grestore } bd\n");
fprintf(fp,"/NP { newpath } bd\n");
fprintf(fp,"/CP { closepath } bd\n");
fprintf(fp,"/CHP { charpath } bd\n");
fprintf(fp,"/CT { curveto } bd\n");
fprintf(fp,"/L { lineto } bd\n");
fprintf(fp,"/RL { rlineto } bd\n");
fprintf(fp,"/M { moveto } bd\n");
fprintf(fp,"/RM { rmoveto } bd\n");
fprintf(fp,"/S { stroke } bd\n");
fprintf(fp,"/F { fill } bd\n");
fprintf(fp,"/TR { translate } bd\n");
fprintf(fp,"/RO { rotate } bd\n");
fprintf(fp,"/SC { scale } bd\n");
fprintf(fp,"/MU { mul } bd\n");
fprintf(fp,"/DI { div } bd\n");
fprintf(fp,"/DU { dup } bd\n");
fprintf(fp,"/NE { neg } bd\n");
fprintf(fp,"/AD { add } bd\n");
fprintf(fp,"/SU { sub } bd\n");
fprintf(fp,"/PO { pop } bd\n");
fprintf(fp,"/EX { exch } bd\n");
fprintf(fp,"/CO { concat } bd\n");
fprintf(fp,"/CL { clip } bd\n");
fprintf(fp,"/EC { eoclip } bd\n");
fprintf(fp,"/EF { eofill } bd\n");
fprintf(fp,"/IM { image } bd\n");
fprintf(fp,"/IMM { imagemask } bd\n");
fprintf(fp,"/ARY { array } bd\n");
fprintf(fp,"/SG { setgray } bd\n");
fprintf(fp,"/RG { setrgbcolor } bd\n");
fprintf(fp,"/SD { setdash } bd\n");
fprintf(fp,"/W { setlinewidth } bd\n");
fprintf(fp,"/SM { setmiterlimit } bd\n");
fprintf(fp,"/SLC { setlinecap } bd\n");
fprintf(fp,"/SLJ { setlinejoin } bd\n");
fprintf(fp,"/SH { show } bd\n");
fprintf(fp,"/FF { findfont } bd\n");
fprintf(fp,"/MS { makefont setfont } bd\n");
fprintf(fp,"/AR { arcto 4 {pop} repeat } bd\n");
fprintf(fp,"/CURP { currentpoint } bd\n");
fprintf(fp,"/FLAT { flattenpath strokepath clip newpath } bd\n");
fprintf(fp,"/TGSM { tgiforigctm setmatrix } def\n");
fprintf(fp,"/TGRM { savematrix setmatrix } def\n");
fprintf(fp,"\n");
fprintf(fp,"end\n");
fprintf(fp,"\n");
fprintf(fp,"%%%%EndProlog\n");
fprintf(fp,"%%%%BeginSetup\n");
fprintf(fp,"%%%%EndSetup\n");
fprintf(fp,"%%%%Page: 1 1\n");
fprintf(fp,"\n");
fprintf(fp,"tgifdict begin\n");
fprintf(fp,"/tgifsavedpage save def\n");
fprintf(fp,"\n");
fprintf(fp,"1 SM\n");
fprintf(fp,"1 W\n");
fprintf(fp,"\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"\n");
fprintf(fp,"72 0 MU 72 11 MU TR\n");
fprintf(fp,"72 128 DI 100.000 MU 100 DI DU NE SC\n");
fprintf(fp,"\n");
fprintf(fp,"GS\n");
fprintf(fp,"\n");
fprintf(fp,"/tgiforigctm matrix currentmatrix def\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      192 128 M\n");
fprintf(fp,"      448 128 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      192 192 M\n");
fprintf(fp,"      448 192 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% BOX\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP 272 112 M 368 112 L 368 128 L 272 128 L CP 1 SG F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP 272 112 M 368 112 L 368 128 L 272 128 L CP EC NP\n");
fprintf(fp,"   pat6 8 264 104 112 32 TGPF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   10 SM\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 272 112 M 368 112 L 368 128 L 272 128 L CP\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      368 112 M\n");
fprintf(fp,"      472 48 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      192 128 M\n");
fprintf(fp,"      288 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      448 128 M\n");
fprintf(fp,"      544 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      368 128 M\n");
fprintf(fp,"      472 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      376 48 M\n");
fprintf(fp,"      472 48 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      472 48 M\n");
fprintf(fp,"      472 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 112 M\n");
fprintf(fp,"      376 48 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      472 64 M\n");
fprintf(fp,"      544 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      288 64 M\n");
fprintf(fp,"      352 64 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% BOX\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP 184 192 M 448 192 L 448 208 L 184 208 L CP 1 SG F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP 184 192 M 448 192 L 448 208 L 184 208 L CP EC NP\n");
fprintf(fp,"   pat6 8 176 184 280 32 TGPF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   10 SM\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      NP 184 192 M 448 192 L 448 208 L 184 208 L CP\n");
fprintf(fp,"      S\n");
fprintf(fp,"   GR\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   448 192 M\n");
fprintf(fp,"   544 128 L\n");
fprintf(fp,"   544 144 L\n");
fprintf(fp,"   448 208 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   1 SG EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EC NP\n");
fprintf(fp,"   pat6 8 440 120 112 96 TGPF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   184 128 M\n");
fprintf(fp,"   184 192 L\n");
fprintf(fp,"   448 192 L\n");
fprintf(fp,"   544 128 L\n");
fprintf(fp,"   544 64 L\n");
fprintf(fp,"   448 128 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   1 SG EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EC NP\n");
fprintf(fp,"   pat3 8 176 56 376 144 TGPF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      448 128 M\n");
fprintf(fp,"      448 192 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   368 112 M\n");
fprintf(fp,"   368 128 L\n");
fprintf(fp,"   472 64 L\n");
fprintf(fp,"   472 48 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   1 SG EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EC NP\n");
fprintf(fp,"   pat6 8 360 40 120 96 TGPF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   368 112 M\n");
fprintf(fp,"   472 48 L\n");
fprintf(fp,"   376 48 L\n");
fprintf(fp,"   272 112 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   1 SG EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EC NP\n");
fprintf(fp,"   pat6 8 264 40 216 80 TGPF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   368 128 M\n");
fprintf(fp,"   472 64 L\n");
fprintf(fp,"   544 64 L\n");
fprintf(fp,"   448 128 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   1 SG EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EC NP\n");
fprintf(fp,"   pat3 8 360 56 192 80 TGPF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLYGON/CLOSED-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP\n");
fprintf(fp,"   272 128 M\n");
fprintf(fp,"   272 112 L\n");
fprintf(fp,"   352 64 L\n");
fprintf(fp,"   280 64 L\n");
fprintf(fp,"   184 128 L\n");
fprintf(fp,"CP\n");
fprintf(fp,"GS\n");
fprintf(fp,"   1 SG EF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   EC NP\n");
fprintf(fp,"   pat3 8 176 56 184 80 TGPF\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      216 128 M\n");
fprintf(fp,"      64 0 atan DU cos 8.000 MU exch sin 8.000 MU RM\n");
fprintf(fp,"      64 0 atan DU cos 8.000 MU 216 exch SU\n");
fprintf(fp,"      exch sin 8.000 MU 192 exch SU L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      216 128 8.000 3.000 0 -64 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      216 128 8.000 3.000 0 -64 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      216 192 8.000 3.000 0 64 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      216 192 8.000 3.000 0 64 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 144 M\n");
fprintf(fp,"      0 96 atan DU cos 8.000 MU exch sin 8.000 MU RM\n");
fprintf(fp,"      0 96 atan DU cos 8.000 MU 368 exch SU\n");
fprintf(fp,"      exch sin 8.000 MU 144 exch SU L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 144 8.000 3.000 -96 0 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 144 8.000 3.000 -96 0 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      368 144 8.000 3.000 96 0 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      368 144 8.000 3.000 96 0 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      256 112 M\n");
fprintf(fp,"      -64 104 atan DU cos 8.000 MU exch sin 8.000 MU RM\n");
fprintf(fp,"      -64 104 atan DU cos 8.000 MU 360 exch SU\n");
fprintf(fp,"      exch sin 8.000 MU 48 exch SU L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      256 112 8.000 3.000 -104 64 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      256 112 8.000 3.000 -104 64 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      360 48 8.000 3.000 104 -64 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      360 48 8.000 3.000 104 -64 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      368 48 M\n");
fprintf(fp,"      344 48 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      264 112 M\n");
fprintf(fp,"      248 112 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      368 136 M\n");
fprintf(fp,"      368 152 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      272 136 M\n");
fprintf(fp,"      272 152 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 303 151 M 322 151 L 322 174 L 303 174 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      304 170 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (W) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 223 151 M 238 151 L 238 174 L 223 174 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      224 170 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (H) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 271 71 M 283 71 L 283 94 L 271 94 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      272 90 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (L) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      488 48 M\n");
fprintf(fp,"      -16 0 atan DU cos 8.000 MU exch sin 8.000 MU RM\n");
fprintf(fp,"      488 32 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      488 48 8.000 3.000 0 16 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      488 48 8.000 3.000 0 16 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      488 64 M\n");
fprintf(fp,"      16 0 atan DU cos 8.000 MU exch sin 8.000 MU RM\n");
fprintf(fp,"      488 80 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      488 64 8.000 3.000 0 -16 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      488 64 8.000 3.000 0 -16 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      480 48 M\n");
fprintf(fp,"      496 48 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 503 39 M 548 39 L 548 62 L 503 62 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      504 58 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (Tmet) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% POLY/OPEN-SPLINE\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"GS\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      472 200 M\n");
fprintf(fp,"      0 24 atan DU cos 8.000 MU exch sin 8.000 MU RM\n");
fprintf(fp,"      496 200 L\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   1 W\n");
fprintf(fp,"   S\n");
fprintf(fp,"GR\n");
fprintf(fp,"GS\n");
fprintf(fp,"   TGSM\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      472 200 8.000 3.000 -24 0 TGAT\n");
fprintf(fp,"   1 SG CP F\n");
fprintf(fp,"   0 SG\n");
fprintf(fp,"   NP\n");
fprintf(fp,"      472 200 8.000 3.000 -24 0 TGAT\n");
fprintf(fp,"   CP F\n");
fprintf(fp,"GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 503 191 M 547 191 L 547 214 L 503 214 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      504 210 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (GND) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 386 163 M 431 163 L 431 186 L 386 186 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      387 182 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (r,Tan) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 433 168 M 443 168 L 443 188 L 433 188 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      434 183 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Symbol FF [20 0 0 -20 0 0] MS\n");
fprintf(fp,"            (d) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 371 153 M 383 153 L 383 186 L 371 186 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      372 178 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Symbol FF [24 0 0 -24 0 0] MS\n");
fprintf(fp,"            (e) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"%% TEXT\n");
fprintf(fp,"NP\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"NP 182 210 M 460 210 L 460 224 L 182 224 L CP 1 SG F\n");
fprintf(fp,"0 SG\n");
fprintf(fp,"   GS\n");
fprintf(fp,"      1 W\n");
fprintf(fp,"      321 222 M\n");
fprintf(fp,"      GS\n");
fprintf(fp,"        GS\n");
fprintf(fp,"        0\n");
fprintf(fp,"            /Helvetica FF [10 0 0 -10 0 0] MS\n");
fprintf(fp,"            ($Id: microstrip.obj,v 1.2 2001/09/13 13:26:20 dan Exp $) TGSW \n");
fprintf(fp,"        AD\n");
fprintf(fp,"        GR\n");
fprintf(fp,"      2 DI NE 0 RM\n");
fprintf(fp,"            0 SG\n");
fprintf(fp,"            /Helvetica FF [10 0 0 -10 0 0] MS\n");
fprintf(fp,"            ($Id: microstrip.obj,v 1.2 2001/09/13 13:26:20 dan Exp $) SH\n");
fprintf(fp,"      GR\n");
fprintf(fp,"   GR\n");
fprintf(fp,"\n");
fprintf(fp,"GR\n");
fprintf(fp,"tgifsavedpage restore\n");
fprintf(fp,"end\n");
fprintf(fp,"showpage\n");
fprintf(fp,"\n");
fprintf(fp,"%%%%Trailer\n");
fprintf(fp,"%%MatchingCreationDate: Sat Sep 15 16:16:24 2001\n");
fprintf(fp,"%%%%DocumentFonts: Symbol\n");
fprintf(fp,"%%%%+ Helvetica\n");
fprintf(fp,"%%%%EOF\n");

/* *********        End of Generated Code           ******** */

fprintf(fp,"\n");
fprintf(fp,"ENDEPSFILE\n");
fprintf(fp,"grestore\n");
fprintf(fp,"moveto\n");

