#!/bin/sh
#
#

This documents what is done to create a wcalc release.  The releases now
are done by branching the sources, fixing up the release version number
in the branch and then tagging the release branch sources.  The motivation
for a branch rather than a tag is to make it easier to deal with setting
the snapshot version number in the documentation, distfile, and the
about dialog box.  

After following the steps below,
upload the 'wcalc-$VERSION.tar.gz' file to the sourceforge file release system

============================================================================

If this is a new year, update the copyright dates in:

COPYING
cgi-wcalc/footer.html
gtk-wcalc/about.c
gtk-wcalc/start.c

============================================================================
To make a wcalc release do the following:


=)      Make sure the version of the shared library in libwcalc/Makefile.am
        is taken care of correctly.

=)	# make sure it makes distfiles ok:
	gmake distclean ; ./autogen.sh  && ./configure && gmake distcheck

=)	cvs ci

=)	update the ChangeLog with 'cvs2cl.pl'.  Check in changes

=)	update the NEWS file with some sort of release notes
	summary.  Check in changes

=)	if this is a major release, then tag and branch:

	1. Tag the base of the release branch
		cvs tag wcalc-1_1-base 

	2. Create the release branch
		cvs tag -R -b -r wcalc-1_1-base wcalc-1_1

	3. On the trunk, update configure.ac to update the version
		and to enable the DEVEL_VERSION define.
		for example 1.1A after branching the 1.1 branch.
		cvs update -PdA
		vi configure.ac
		cvs ci configure.ac

	4. On the release branch, update configure.ac to 
		update the version
		for example 1_1_ALPHA.  Now pre-release snapshots can be made.
		cvs update -PdA -r wcalc-1_1

	5. If desired tag an alpha release:
		cvs update -PdA -r wcalc-1_1
		./autogen.sh
		cvs tag -R -r wcalc-1_1 wcalc-1_1-ALPHA
		cvs update -PdA -r wcalc-1_1-ALPHA
		./autogen.sh && ./configure && gmake distcheck

	6. When the release branch is ready to go,  update configure.ac
	   to set the final release version and to disable the DEVEL_VERSION define.
		Then tag the release.
		cvs update -PdA -r wcalc-1_1
		vi configure.ac
		cvs ci configure.ac
		./autogen.sh
		cvs ci
		cvs tag -R -r wcalc-1_1 wcalc-1_1-RELEASE
		cvs update -PdA -r wcalc-1_1-RELEASE
		./autogen.sh && gmake distcheck

	7. Return to your regularly scheduled trunk development
		cvs update -PdA

=) 	if this is a patch release, then simply make desired changes to the branch, and
		./autogen.sh 
		cvs ci
		cvs tag -R -r wcalc-1_1 wcalc-1_1-PATCH001

=)	gmake distclean ; ./autogen.sh && gmake distcheck

=)	Copy the distfile to cygwin and do
	cd src
	tar -zxvf wcalc-1.1.tar.gz
	cd wcalc-1.1
	sh win32/build_wcalc
	Copy the resulting installer (wcalcinst-1.1.exe and wcalcinst-1.1.zip)

=)	Create checksums

		openssl sha1 wcalc-1.1.tar.gz wcalcinst-1.1.* > wcalc-1.1.cksum
		openssl md5 wcalc-1.1.tar.gz wcalcinst-1.1.* >> wcalc-1.1.cksum
		openssl rmd160 wcalc-1.1.tar.gz wcalcinst-1.1.* >> wcalc-1.1.cksum


=)      Create a new file release for the package "gerbv" with a release name of
        "gerbv-2.2.0" (for gerbv-2.2.0).  Do this by logging into www.sourceforge.net
        and then navigating to

        https://sourceforge.net/projects/gerbv  (you must be logged in to sourceforge)

        Pick Admin->File Releases

        Next to the "gerbv" package, click "Add Release"

        In the "Step 1:  Edit Existing Release" section, paste in the section of the NEWS
        for this version.  Check the "Preserve my pre-formatted text" radio button and click
        "Submit/Refresh".

        In the "Step 2: Add Files To This Release" section follow the "upload new files" link
        and then in the next page the "Web Upload" link.  You will have to log in to
        sourceforge again.

        Upload the .tar.gz, .cksum, and if you built one, the windows installer.

        Once you have completed the file uploads return to the edit releases page, check
        the radio buttons next to the uploaded files and click the "Add Files..." button.

        In the "Step 3:  Edit Files in this Release" section, set the following:
             For file types:
                     .tar.gz  -  any / source .gz
                     .cksum   -  Platform Independent / Other Source File
                     .exe     -  i386 / .exe (32-bit Windows)

        You will have to click "update" for each file as you go.

        In the "Step 4:  Email Release Notice" section, check the "I'm sure" 
        radio button and click the "Send Notice" button.
        
=)      Have a project admin go to the Admin->File Releases page and then
        follow the "Create/Edit Download page" to change the default download
        file to the new release.

=)      Return to trunk development with
        cvs update -PdA


