#!/bin/sh
#
# $Id: README-to-release,v 1.6 2006/02/09 13:47:25 dan Exp $
#

This documents what is done to create a wcalc release.  The releases now
are done by branching the sources, fixing up the release version number
in the branch and then tagging the release branch sources.  The motivation
for a branch rather than a tag is to make it easier to deal with setting
the snapshot version number in the documentation, distfile, and the
about dialog box.  

After following the steps below,
upload the 'wcalc-$VERSION.tar.gz' file to the sourceforge file release system

============================================================================

If this is a new year, update the copyright dates in:

COPYING
cgi-wcalc/footer.html
gtk-wcalc/about.c
gtk-wcalc/start.c

============================================================================
To make a wcalc release do the following:


=)      Make sure the version of the shared library in libwcalc/Makefile.am
        is taken care of correctly.

=)	# make sure it makes distfiles ok:
	gmake distclean ; ./autogen.sh  && ./configure && gmake distcheck

=)	cvs ci

=)	update the ChangeLog with 'cvs2cl.pl'.  Check in changes

=)	update the NEWS file with some sort of release notes
	summary.  Check in changes

=)	if this is a major release, then tag and branch:

	1. Tag the base of the release branch
		cvs tag wcalc-0_9-base 

	2. Create the release branch
		cvs tag -R -b -r wcalc-0_9-base wcalc-0_9

	3. FIX_ME [fix up this step.  what shall we do with the version
	   on the trunk?]
	   On the trunk, update configure.in and win32/build_wcalc to update the version
		and to enable the DEVEL_VERSION define.
		for example 1.99x after releasing 1.99w
		cvs update -PdA
		vi configure.in win32/build_wcalc
		cvs ci configure.in win32/build_wcalc

	4. On the release branch, update configure.in and win32/build_wcalc to 
		update the version
		for example 0_9_ALPHA.  Now pre-release snapshots can be made.
		cvs update -PdA -r wcalc-0_9

	5. If desired tag an alpha release:
		cvs update -PdA -r wcalc-0_9
		./autogen.sh
		cvs tag -R -r wcalc-0_9 wcalc-0_9-ALPHA
		cvs update -PdA -r wcalc-0_9-ALPHA
		./autogen.sh && ./configure && gmake distcheck

	6. When the release branch is ready to go,  update configure.in and
	   win32/build_wcalc to
	   set the final release version
		and to disable the DEVEL_VERSION define.
		Then tag the release.
		cvs update -PdA -r wcalc-0_9
		vi configure.in win32/build_wcalc
		cvs ci configure.in win32/build_wcalc
		./autogen.sh
		cvs ci
		cvs tag -R -r wcalc-0_9 wcalc-0_9-RELEASE
		cvs update -PdA -r wcalc-0_9-RELEASE
		./autogen.sh && gmake distcheck

	7. Return to your regularly scheduled trunk development
		cvs update -PdA

=) 	if this is a patch release, then simply make desired changes to the branch, and
		./autogen.sh 
		cvs ci
		cvs tag -R -r wcalc-0_9 wcalc-0_9-PATCH001

=)	gmake distclean ; ./autogen.sh && gmake distcheck

=)	Copy the distfile to cygwin and do
	cd src
	tar -zxvf wcalc-1.0.tar.gz
	cd wcalc-1.0
	sh win32/build_wcalc
	Copy the resulting installer (wcinst-1.0.exe and wcinst-1.0.zip)

=)	Create checksums

		digest sha1 wcalc-1.0.tar.gz wcinst-1.0.* > wcalc-1.0.SHA1
		digest md5 wcalc-1.0.tar.gz wcinst-1.0.* > wcalc-1.0.MD5

=)	Upload the .tar.gz, .MD5, .SHA1, and win32/wcinst-*.{exe,zip} files
	to ftp://upload.sourceforge.net/incoming/

=)	Create a new file release for wcalc with a release name of
	"wcalc-1.0" (for wcalc-1.0).

=)	For file types:

	.tar.gz      -  any / source .gz
	.{SHA1,MD5}  -  Platform Independent / Other Source File
	.exe         -  i386 / .exe (32-bit Windows)
	.zip         -  i386 / .zip

