name: Wcalc CI - Common

runs:
  using: "composite"
  steps:
    - name: Autogen
      shell: bash
      run: ./autogen.sh

    - name: Post-autogen workarounds
      shell: bash
      run: |
        touch intl/ChangeLog

    - name: Configure
      shell: bash
      run: ./configure

    - name: Debug
      shell: bash
      run: |
        bison --version
        convert --version
        ls -l $(which tgif)

    - name: Build
      shell: bash
      run: |
        echo "Running: $XVFB_RUN make"
        $XVFB_RUN -- make

    - name: Test stdio-wcalc
      shell: bash
      run: cd stdio-wcalc && ./run_tests.sh --show-diffs

    - name: Distcheck
      shell: bash
      run:  |
        echo "Running: $XVFB_RUN make distcheck"
        $XVFB_RUN -- make distcheck

    - name: Upload Tarball
      shell: bash
      uses: actions/artifact-upload@v4
      with:
        name: wcalc-1.1A
        path: wcalc-1.1A.tar.gz