.\" $Id: ic_microstrip_calc.man,v 1.3 2001/11/03 19:21:48 dan Exp $
.\"
.\" Copyright (c) 2001 Dan McMahill
.\" All rights reserved.
.\"
.\" This code is derived from software written by Dan McMahill
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and.\"or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"        This product includes software developed by Dan McMahill
.\"  4. The name of the author may not be used to endorse or promote products
.\"     derived from this software without specific prior written permission.
.\" 
.\"  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\"  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\"  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\"  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\"  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
.\"  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\"  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
.\"  AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\"  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\"  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\"  SUCH DAMAGE.
.\"

.TH ic_microstrip_calc 1 "March 2001" "Dan McMahill" "Wcalc"
.\".so ../sci.an
.SH NAME
ic_microstrip_calc - Integrated circuit microstrip transmission line analysis
.SH CALLING SEQUENCE
.nf
[z0,L,R,C,G] = 
    ic_microstrip_calc(w,l,tox,eox,h,es,sigmas,tmet,rho,rough,f);
.fi
.SH PARAMETERS
.TP 10
w
: width of microstrip line (meters)
.TP
l
: lentgh of microstrip line (meters)
.TP
tox
: oxide thickness (meters)
.TP
eox
: oxide relative permitivity
.TP
h
: substrate thickness (meters)
.TP
es
: substrate relative permitivity
.TP
sigmas
: substrate conductivity (1/ohm-m)
.TP
tmet
: metal thickness (meters)
.TP
rho
: resistivity of the metal (ohm-m)
.TP
rough
: conductor surface roughness (meters-rms)
.TP
f
: analysis frequency (Hz)
.TP
z0
: calculated characteristic impedance (Ohms)
.TP
keff
: calculated effective relative permitivitty
.TP
loss
: calculated loss of the line (dB)
.TP
deltal
: calculated open circuit end correction (meters)
.SH DESCRIPTION
function to analyze the electrical characteristics of a single 
integrated circuit microstrip transmission line. The physical
dimensions of the microstrip line are given as inputs and the
characteristic impedance, effective dielectric constant, loss and
open circuit end correction are calculated.
.nf

                 |<--W-->|
                  _______    
                 | metal | <- tmet,rho,rough
    ----------------------------------------------
   {**************  Oxide (tox,eox) **************
    ----------------------------------------------
   (  substrate                          /|\\     (
    )   es,sigmas                     H   |       )
   (                                     \\|/     (
    ----------------------------------------------
    XXXXXXXXXXXXXXXXXX ground XXXXXXXXXXXXXXXXXXXX

.fi
.SH EXAMPLE
.nf
w=150e-6;          // width 
h=250e-6;          // substrate height
l=1000e-6;         // length
es=11.8;           // substrate permitivitty
sigmas=0.5;        // substrate conductivity
tox=1.5e-6;        // oxide thickness
eox=4;             // oxide permitivitty
tmet=0.8e-6;       // metal thickenss
rho=3.0e-8;        // metal resitivity
rough=0.0;         // metal surface roughness
f=2.4e9;           // frequency
[z0,L,R,C,G] = ic_microstrip_calc(w,l,tox,eox,h,es,sigmas,tmet,rho,rough,f);
disp(sprintf('z0 = %8.4g + j %8.4g Ohms', real(z0), imag(z0) ));
disp(sprintf('L  = %8.4g nH/mm', L*1e6));
disp(sprintf('R  = %8.4g Ohm/mm', R*1e-3));
disp(sprintf('C  = %8.4g fF/mm', C*1e12));
disp(sprintf('G  = %8.4g uMho/mm', G*1e3));
.fi
.SH SEE ALSO
ic_microstrip_syn
.SH AUTHOR
Dan McMahill
