#!/bin/sh
#
#
# Copyright (c) 2004, 2005, 2009 Dan McMahill
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 
LIBTOOL=../libtool
CC=$1
libdir=$2
pkglibexecdir=$3
MEXSFX=$4
shift 4

args=""

while test $# -ne 0 ; do
	case $1 in
	-o )
		# some versions of mex may include MEXSFX and others
		# may not, so strip that part off and explicitly put it
		# back.
		args="$args -o `dirname ${2}`/`basename ${2} .${MEXSFX}`.${MEXSFX}.la"
		shift 2
		;;

	*.o )
		args="$args `echo $1 | sed 's;\.o;.lo;g'`"
		shift
		;;

	* )
		args="$args $1"
		shift
		;;
	esac
done

set -x
$LIBTOOL --mode=link $CC -avoid-version -export-dynamic -module -shrext '""' -rpath $pkglibexecdir $args

