name: Wcalc CI - MacOS

on:
  push:
    branches:
      - develop
      - 'dev-*'
      - 'ci-*'
  pull_request:
    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew update
          brew install autoconf
          brew install automake
          brew install coreutils
          brew install gawk
          brew install gettext
          brew install groff
          brew install gtk+
          brew install imagemagick
          brew install netpbm
          brew install pstoedit
          brew install tgif
          brew install util-linux
          brew install w3m
          brew install libxslt
          brew install --cask xquartz
          brew install xauth

      - name: Homebrew netpbm workaround
        run: |
          # this ships with netpbm but was giving
          # some colors names in the ppmtoxpm output
          # that
          #   convert --colors 16 foo.xpm foo_16.ppm
          # didn't like
          #RGBDEF="$(brew list netpbm | grep rgb.txt)"
          # but this one from XQuartz seems to work
          RGBDEF=/opt/X11/share/X11/rgb.txt
          echo "Setting: RGBDEF=${RGBDEF}"
          echo "RGBDEF=${RGBDEF}" >> $GITHUB_ENV

      - name: xvfb-run
        run: |
          echo "XVFB_RUN=ci-scripts/xvfb-run --auto-servernum  --error-file xvfb-run-errors.log" >> $GITHUB_ENV
          echo "PATH=/opt/X11/bin:/usr/local/opt/util-linux/bin:${PATH}" >> $GITHUB_ENV

          # Xvfb really wants this directory to exist and be owned by root
          sudo mkdir -p -m1777 /tmp/.X11-unix

      - name: Common
        uses: ./.github/workflows/common
